<?php
    $lang['number']   = 'Numer';
    $lang['date']     = 'Data';
    $lang['time']     = 'Godzina';
    $lang['due']      = 'Termin płatności';
    $lang['to']       = 'Nabywca';
    $lang['from']     = 'Sprzedawca';
    $lang['product']  = 'Nazwa usługi';
    $lang['qty']      = 'Ilość';
    $lang['price']    = 'Cena netto';
    $lang['discount'] = 'VAT';
    $lang['vat']      = 'PKWiU';
    $lang['total']    = 'Razem';
    $lang['page']     = 'Strona';
    $lang['page_of']  = 'z';
